spring.application.name=e-commerce

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=M@nthan2104
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

jwt.secretkey = kah9#2i1@oi325o44@joi&&sdfgkjdsgsmksytarg


